## <strong>2. NumPy: Universal Functions (UFunc)</strong>

In [1]:
import numpy as np

In [5]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# [+] 함수 테스트
values = np.random.randint(1, 10, size=5)

In [7]:
values

array([9, 1, 1, 7, 5], dtype=int32)

In [9]:
compute_reciprocals(values)

array([0.11111111, 1.        , 1.        , 0.14285714, 0.2       ])

#### <strong>역수 계산: Python loop vs NumPy ufuncs</strong>
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [20]:
# [+] 백만 개 크기의 난수 배열 생성: 정수, 값 범위 [1, 100) [ -> 포함, 미포함 <- )
array = np.random.randint(1, 100, size=1000000)

In [21]:
%%timeit

# [+] Python loop를 통한 역수 계산 
def c_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

66.3 ns ± 1.81 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [30]:
%%timeit
1 / array
# 넘파이에 들어있는 각각의 원소에 대한 역수를 계산
# 나눗셉의 대상이 ndarray일 경우 그 전용의 유니버설 함수 불러옴
# vectorized code가 빠른 이유는 기존 파이썬의 반복문은 모든 과정에서 매번 python 연산이 실행된다고 하면,
# 벡터화되면 c=a+b 있다고 할 때 a+b만 파이썬으로 돌리고 나머지 연산은 넘파이 내부에서 C로 작성된
# 코드가 실행되고 내부에서 루프로 돌면서 게산된다. a+b 연산 자체가 C로 수행되는 것.

2.55 ms ± 176 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### <strong>유니버설 함수들</strong>

In [24]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [25]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

[ 3  6  7  3 -2]


In [26]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

[ 3  7 14  9  7]


In [27]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [31]:
"""
    UFuncs: 산술 연산
"""

# 기본 산술 연산
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("x ** 2 =", np.power(x, 2))


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [41]:
"""
    UFuncs: 절댓값 계산
"""

# [+] 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)
...

Ellipsis

In [33]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = np.linspace(0,100,5)
x

array([  0.,  25.,  50.,  75., 100.])

In [38]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 11)
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [42]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [43]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [44]:
# [+] 덧셈 연산으로 집계
aggr = np.add.reduce(x)
aggr

np.int64(10)

In [48]:
# [+] 곱셈 연산으로 집계
aggr = int(np.multiply.reduce(x))
aggr

24

In [51]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = np.add.accumulate(x)[:3]
accum

array([1, 3, 6])

In [56]:
# [+] 곱셈 연산으로 집계
accum = np.multiply.accumulate(x)
accum1 = np.multiply.accumulate(x)[:3]

accum, accum1

(array([ 1,  2,  6, 24]), array([1, 2, 6]))

In [57]:
accum = np.subtract.accumulate(x)
accum

array([ 1, -1, -4, -8])

In [59]:
# 집계 함수: sum()
np.random.seed(3)
arr = np.random.rand(1000000) # [+] 0~1 사이의 실수 형태의 난수 배열 생성

print(arr)
print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015305


In [66]:
rng = np.random.default_rng()
arr = rng.random((2,3))
arr.min(), arr.max()

(np.float64(0.15633716575316414), np.float64(0.9426760582921558))

In [67]:
# sum(): Python 내장함수
%timeit sum(arr)

2.2 μs ± 18.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [68]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

2.69 μs ± 110 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [81]:
# [+] 그 외의 집계함수
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr, 90))
print("variance =", np.var(arr))
print("standard deviation =", np.std(arr))
print("index of maximum value =", np.argmax(arr))
print("index of minimum value =", np.argmin(arr))
print("Is there any number greater than 1? =", np.any(arr > 1))
print("Is every number greater than 0? =", np.all(arr > 0)) 

max = 0.9426760582921558
min = 0.15633716575316414
mean = 0.6220440854179647
median = 0.6567371097371029
percentile = 0.9251771418503119
variance = 0.08377162787584952
standard deviation = 0.28943328743572244
index of maximum value = 3
index of minimum value = 2
Is there any number greater than 1? = False
Is every number greater than 0? = True


In [82]:
"""다차원 집계"""

# 2차원 난수 배열 생성
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [84]:
# [+] 행 방향으로 집계 (row sum)
row_sum = np.sum(arr, axis=1)
row_sum

array([11, 24, 19])

In [86]:
# [+] 열 방향으로 집계 (column sum)
col_sum = np.sum(arr, axis=0)
col_sum

array([14, 13, 13, 14])

In [90]:
int(np.sum(arr))

54